import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: root });

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      // Regenerated by `next build` on every run, and Next writes the triple-slash
      // reference that `@typescript-eslint/triple-slash-reference` rejects.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      /* An underscore prefix is an explicit "unused on purpose". Every other
         unused binding still fails. */
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
];

export default config;
